### ISSUE TITLE
replace compiledin default patterns with only "base" ones

### ISSUE THREAD

**Issue by vjeantet** [vjeantet/grok#12]
Hello,

Currently, 13905 allocations are performed when calling a Grok.New(), about 11ms on my MBPro

If I replace the current patterns.go with one containing only expressions found in the [base file](https://github.com/gemsi/grok/blob/master/patterns/base)
Grok.New() performs 5502 allocations during 2,4 ms on the same MBPro.

What do you think about making patterns.go lighter ?

**Comment by palmerabollo** [comment]
I don't have a strong opinion.

On one hand, ```Grok.New``` is not something you call very frequently (usually once during initialization) so 8ms is not a big deal.

On the other, I think that expressions in gemsi/grok are outdated compared to [the "official" ones](https://github.com/logstash-plugins/logstash-patterns-core/tree/master/patterns). It is something hard to maintain and keep up to date.

Said that, what I'd do is:
- Simplify patterns.go the way you propose. This change breaks backwards compatibility (for people already using some grok expressions), so I'd tag current version as 1.0.0 and make the change in 2.x.
- Add a new configuration property (```PatternsDir``` if we want to use the same [name already used in logstash](https://www.elastic.co/guide/en/logstash/current/plugins-filters-grok.html#plugins-filters-grok-patterns_dir)) for those who want to load additional expressions.

  ```go
   g := grok.NewWithConfig(&grok.Config{PatternsDir: pathToADir})
  ```
