### ISSUE TITLE
Export the Grok.compile and Grok.compiledparse ?

### ISSUE THREAD

**Issue by buixor** [vjeantet/grok#19]
Hello,

Wouldn't it be cool to make `Grok.Compile()` and `Grok.CompiledParse()` exported ?
It is usually considered a good practice to compile regex in advance. Or maybe there is another way to do it and I didn't understand/read the doc properly,

ps: If you agree, I can submit a MR because I made the modifications locally.

Thanks !

**Comment by vjeantet** [comment]
Hello @buixor, already done.

regex are compiled on first use, then cached for later use
see here : https://github.com/vjeantet/grok/blob/master/grok.go#L289
