### ISSUE TITLE
please version grok

### ISSUE THREAD

**Issue by aviau** [vjeantet/grok#21]
Hello,

Could you please tag this repository?

I am the Debian Maintainer for this project and tags would help Debian keep up with new releases/bugfixes.

See:
- http://semver.org/
- http://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases

**Comment by vjeantet** [comment]
Hello, 

  how this library can be used in a distrib like debian ? It is not an app.

**Comment by vjeantet** [comment]
tagged

**Comment by aviau** [comment]
> how this library can be used in a distrib like debian 

Debian has programs, which are built with libraries. Programs don't include the source code of all of the libraries they use.
