### ISSUE TITLE
multiline support

### ISSUE THREAD

**Issue by ganting** [vjeantet/grok#22]
i want to parse multiline with grok

`g, _ := NewWithConfig(&Config{NamedCapturesOnly: true})`

`text := "2017-09-20T13:42:38.349+8:00 error login [http-nio-8081-exec-6] [LogServiceImpl] <2eaad87b6c3443fa9ca0e4f3e5402b2d,0_1_2> [0x00105091] - this is a log195\n  com.logstore.exception.ProgramException: java.text.ParseException: Unparseable date: \"2017-08-01T20:15:12.342+07:00\"\n"`

`captures, _ := g.Parse("(?m)%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{NOTSPACE:module} \\[%{NOTSPACE:threadNo}\\] \\[%{NOTSPACE:methodName}\\] <%{NOTSPACE:traceId},%{NOTSPACE:rpcId}> \\[%{NOTSPACE:errorCode}\\] - %{GREEDYDATA:message}", text);`

```
for k, v := range captures {
		fmt.Println(k, "=", v)
	}
```

==========================ouput================
level = error
module = login
threadNo = http-nio-8081-exec-6
methodName = LogServiceImpl
rpcId = 0_1_2
errorCode = 0x00105091
timestamp = 2017-09-20T13:42:38.349+8:00
traceId = 2eaad87b6c3443fa9ca0e4f3e5402b2d
message = this is a log195

the message field parsed by grok is not correct! please help me,  thanks!

**Comment by vjeantet** [comment]
Hello @ganting 

All GREEDYDATA is is .*, but . doesn't match newline.

you may try something like `(?<message>(.|\r|\n)*)` instead of `%{GREEDYDATA:message}`

**Comment by ganting** [comment]
thanks， this way is ok!
